services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - backend

  kafka1:
    image: apache/kafka:latest
    container_name: kafka1
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://kafka1:9092,CONTROLLER://kafka1:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka1:9093,2@kafka2:9095
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 2
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
    ports:
      - "9092:9092"
    networks:
      - backend

  kafka2:
    image: apache/kafka:latest
    container_name: kafka2
    environment:
      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://kafka2:9094,CONTROLLER://kafka2:9095
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9094
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka1:9093,2@kafka2:9095
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 2
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
    ports:
      - "9094:9094"
    networks:
      - backend
    depends_on:
      - kafka1

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8080:8080"
    environment:
      DYNAMIC_CONFIG_ENABLED: "TRUE"
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka1:9092,kafka2:9094
    depends_on:
      - kafka1
      - kafka2
    networks:
      - backend

  df:
    build:
      context: ..
      dockerfile: services/dataForwardingService/Dockerfile
    container_name: df
    depends_on:
      - redis
      - kafka1
      - kafka2
    environment:
      PORT: 54342
      REDIS_ADDR: redis:6379
      KAFKA_BROKER: kafka1:9092,kafka2:9094
    ports:
      - "54342:54342"
    networks:
      - backend

  df2:
    build:
      context: ..
      dockerfile: services/dataForwardingService/Dockerfile
    container_name: df2
    depends_on:
      - redis
      - kafka1
      - kafka2
    environment:
      PORT: 54343
      REDIS_ADDR: redis:6379
      KAFKA_BROKER: kafka1:9092,kafka2:9094
    ports:
      - "54343:54343"
    networks:
      - backend

  auth_service:
    build:
      context: ..
      dockerfile: services/authService/Dockerfile
    container_name: authService
    environment:
      PGSQL_DSN: ${PGSQL_DSN}
    ports:
      - "50051:50051"
    networks:
      - backend

networks:
  backend:
    driver: bridge